### ISSUE TITLE
Ergänze operationId-Property für sämtliche Methoden in OpenAPI

### ISSUE THREAD

**Issue by aldafu** [Schulconnex/Schulconnex#120]
- hilft bei potentieller Codegenerierung für SDKs
- beseitigt Warnung bei OpenAPI-Validierung

**Comment by bwhdien** [comment]
Es darf weder jetzt noch in Zukunft Dopplungen der Operation IDs geben, daher sollte m. E. die Operation ID dem Pfad entsprechen. 
Auch leicht verwechselbare Operation IDs (readPersonenkontexteID, readPersonenkontexID) sollten m. E. vermieden werden.
