### ISSUE TITLE
Label für die API-Methoden (Sidebar method labels)

### ISSUE THREAD

**Issue by bwhdien** [Schulconnex/Schulconnex#130]
Es ist hilfreich, wenn die HTTP-Methode im Menü (Sidebar) der API-Endpunkte deutlich erkennbar ist. Daher sollten farbige Label hinzugefügt werden. 

![image](https://github.com/user-attachments/assets/0753f064-877b-4297-bce7-aa63011c1533)

**Comment by AnnikaStrupp-initAG** [comment]
Votum in Veranstaltung siehe Screenshot.

<img width="214" alt="optionen_menu" src="https://github.com/user-attachments/assets/e13c9fef-c7d5-4130-ad12-f7bc9f1ad29e">
