### ISSUE TITLE
Kennzeichnung von normativen und nichtnormativen Teilen der Webseite

### ISSUE THREAD

**Issue by bwhdien** [Schulconnex/Schulconnex#131]
Die Webseite wird neben der Spezifikation noch weitere Informationen zu Schulconnex enthalten werden müssen. 

Die Teile der Spezifikation sind die bindenden bzw. "normativen" Teilen. Eine inhaltliche Änderung dieser Teile führt zu einer Versionsänderung der Spezifikation. 

Auf die nichtnormativen Teile trifft das nicht zu.

**Comment by gorkemg** [comment]
Tags können genutzt werden, um Seiten klar als normativ bzw. nicht normativ zu kennzeichnen.

**Comment by gorkemg** [comment]
Es werden zwei Tags hinzugefügt: _Verbindlich_ und _Informativ_
Zusätzlich können Infoboxen in Texte hinzugefügt werden, die einen Abschnitt als _Verbindlich_ oder als _Informativ_ kennzeichnen.
Beispiel-Text der Infobox _Verbindlich_: "Dieser Teil ist verbindlich"
Beispiel-Text der Infobox _Informativ_: „Dieser Teil ist nicht verbindlich und dient nur zur Information“

**Comment by gorkemg** [comment]
## Vorschläge für Seiten

### Verbindliche Seiten
- Schnittstellendefinition
- Fehlerbehandlung
- Validierung
- OIDC-Claims

### Informative Seiten
- Autorisierung Dienstanbieter
- Autorisierung Quellsysteme
- Anbieterspezifische Attribute
- Synchronisation Quellsystem
- Ablauf Schuljahrwechsel
- Änderung der Rolle in einer Organisation
- Löschen von Personen
- Glossar

Für weitere Vorschläge bzw. Anpassung der Liste bin ich offen.

**Comment by bwhdien** [comment]
Anbieterspezifische Attribute auftrennen in einen verbindliche Seite und eine informative Seite (Best Practice für anbieterspezifische Attribute)
