### ISSUE TITLE
In den JSON Schemas und in der Dokumentation kennzeichnen, wenn ein Attribut die ID eines existierenden Datenbankobjekts ist

### ISSUE THREAD

**Issue by bwhdien** [Schulconnex/Schulconnex#150]
Manche Attribute wie "ktid", "orgid", "id" stellen immer ID-Werte da, die andere existierende Objekte desselben Schulconnex-Servers referenzieren müssen. Dies sollte an allen Stellen gekennzeichnet sein. 

Die Auszeichnung "format: uuid" reicht nicht aus bzw. ist u. U. sogar falsch, da Schulconnex-Server nicht gezwungen sind, Identitäten im Format UUID zu halten.

**Comment by bwhdien** [comment]
@aldafu Möglicherweise brauchen wir eine Schemaerweiterung wie hier beschrieben https://json-schema.org/understanding-json-schema/reference/schema, z. B. "isID: true" oder "isReferenz: true"

**Comment by bwhdien** [comment]
Am besten wäre wohl "isResourceIdentifier".

**Comment by AnnikaStrupp-initAG** [comment]
Hintergrund zu "format" (Henry Andrews, OpenAPI Initiative) von 2021 https://github.com/OAI/OpenAPI-Specification/issues/845#issuecomment-783793032

Siehe auch Entwurf einer JSON Schema "format registry" von 2023 https://github.com/OAI/OpenAPI-Specification/issues/845#issuecomment-1434615546 (OpenAPI Initiative)

JSON Schema: "By default, format is just an annotation and does not effect validation."
https://json-schema.org/understanding-json-schema/reference/string#format
https://tour.json-schema.org/content/08-Annotating-JSON-Schemas/04-format-and-examples

OpenAPI 3.0.3: "However, to support documentation needs, the format property is an open string-valued property, and can have any value. "
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#data-types

OpenAPI 3.1.0: Verweis auf https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-7. Zu prüfen: "Format-Annotation Vocabulary" oder "Format-Assertion Vocabulary"

**Comment by AnnikaStrupp-initAG** [comment]
**Einschätzung:** JSON Schema und OpenAPI 3.0 lassen eigene Werte in "format" zu. Eine Schemaerweiterung ist nicht erforderlich. Tools können "format" zur Validierung nutzen oder ignorieren.

**Comment by AnnikaStrupp-initAG** [comment]
**Zu entscheiden bis 2. Oktober 2024:**

- Modifier "format: uuid" entfernen? (beachte auch Wert in: "example:")
- Eigenen Wert in "format:" angeben?
- Einheitliche Beschreibung in "description:" ergänzen?

**Comment by aldafu** [comment]
- überall `format: uuid` entfernen und durch `example: ...` ersetzen, zu klären was genau als bsp für die verschieden arten von id zu verwenden ist.
- beschreibung überall ergänzen zur semantik der verschieden varianten von id

**Comment by bwhdien** [comment]
Entscheidung zur Umsetzung:

* "format: uuid" überall entfernen. 
* 128-bit UUID in der üblichen Formatierung in der QS-API als Beispiele belassen
* Dienste-API: 64 Zeichen lange Zufallsstrings verwenden bei den personenbezogenen IDs (pid, ktid, Gruppenzugehörigkeiten) 
* IDs in den Beispielen konsistent halten
