### ISSUE TITLE
Nicht kodierte Schulfächer zulassen

### ISSUE THREAD

**Issue by bwhdien** [Schulconnex/Schulconnex#173]
Nicht alle Schulfächer stehen als Codes zur Verfügung. Insb. Schulen in freier Trägerschaft haben oft einen Fächerkanon mit anderen Fachnamen. Diese müssten aktuell entweder eigener Codelisten verwenden oder den Fachname als gruppe.thema eintragen. Es sollte eine Lösung definiert werden, z. B. gruppe.faecher[].name oder gruppe.fachname

**Comment by bwhdien** [comment]
Alternativen: 

* gruppe.faecher[].name
* gruppe.faecher[].fachname
* gruppe.faecher[].bezeichnung (präferiert, weil für den Anzeigenamen der Gruppe auch bezeichnung verwendet wird)
* gruppe.fachname

GGf. muss festgelegt werden, ob gruppe.faecher[].kennung zugleich gesetzt werden darf, inkl. Error-handling.

**Comment by ChristianFuhrhop** [comment]
Am sinnvollsten finde ich eine Alternative oder einen Zusatz zu Kennung, da dort auch die Codes für die gelisteten Fächer stehen. An allen anderen Stellen hätte man plötzlich eine andere Funktion der Felder.
Also entweder:
  "faecher": [
    {
      "kennung": "N.N."
      "name": "Holzschnitzen"
    }
  ],
oder
  "faecher": [
    {
      "name": "Holzschnitzen"
    }
  ],
Die erste Version (mit Kennung, welche angibt, dass ein Fach nicht in der Liste ist) würde ich vorziehen. Damit bleibt "kennung" weiter mandatory, und auch Quell-Systeme, welche das Fach nicht kennen, können zumindest auf "N.N." reagieren.

Bezeichnung kann zu leicht zu Verwechslungen mit der Gruppenbezeichnung führen, Fachname passt nicht gut zu der sonstigen Namensgebung (wir nutzen ja auch nicht Gruppenbezeichnung oder Fächerkennung). 
"gruppe.fachname" passt nicht wenn mehrere Fächer gelistet werden sollen, es sollte schon weiterhin unter gruppe.faecher[] verortet sein.

**Comment by bwhdien** [comment]
Entscheidung für "gruppe.faecher[].bezeichnung". 
Falls "bezeichnung" und "kennung" gesetzt sind, muss validiert werden, dass die Bezeichnung der Bezeichnung zum Codewert entspricht. 
* Entweder 400 03 plus spezifische Fehlermeldung 
* Oder neuen Fehlercode speziell, wenn Code und Code-Bezeichnung nicht zusammenpassen. 

Separate Tickets für:
* Weiteres Attribut "kuerzel" (1.6)
* Filterfunktionen ergänzen (1.6)
