### ISSUE TITLE
Version 1.5 veröffentlichen

### ISSUE THREAD

**Issue by bwhdien** [Schulconnex/Schulconnex#217]
- [ ] Version im Quelltext an 4 Stellen anpassen
- [ ] VERSION_PATH entfernen
- [ ] Datenschutzerklärung austauschen

**Comment by AnnikaStrupp-initAG** [comment]
Wichtig: @petrakow verweist bzgl. Versionierung auf https://tutorial.docusaurus.io/docs/tutorial-extras/manage-docs-versions/

Damit kann die mit https://github.com/Schulconnex/Schulconnex/commit/95722e2665e75d23456fa78525fb19409961e110 in docusaurus.config.ts eingeführte `const VERSION_PATH = '1.5'` wegfallen. Rückfragen gerne über mich an André Petrakow.

**Comment by bwhdien** [comment]
@AnnikaStrupp-initAG @petrakow , müsste das vor dem Livegang von 1.5 geändert werden?

**Comment by petrakow** [comment]
@bwhdien, sofern eine eventuelle Version 1.0 (1.4?) nicht publiziert werden soll, wäre es nicht notwendig. Dann würde die Initiale Version 1.5 sein und später dann 1.6 als "Current" gelten.
Die Aktuelle Version wäre dann immer unter `/docs` (z.B. 1.6 wenn released); alle historischen Versionen wären unter `versioned_docs/[version]/docs` (z.B. versioned_docs/1.5/docs)

**Comment by AnnikaStrupp-initAG** [comment]
@bwhdien bzgl. API-Refinement vom 1.11.2024 "Anleitung/Prozess für künftige Versionsänderung" sollte hier ab Version 1.6 die von Docusaurus vorgesehene Versionierung umgesetzt werden. Siehe oben https://tutorial.docusaurus.io/docs/tutorial-extras/manage-docs-versions/

@aldafu
@petrakow

**Comment by AnnikaStrupp-initAG** [comment]
siehe auch Beispiele und Tipps zur Umsetzung unter https://docusaurus.io/docs/versioning

**Comment by AnnikaStrupp-initAG** [comment]
Entscheidung für v1.5: vermeiden, dass vor Veröffentlichung von v1.5 md-Dateien verschoben werden müssen.
