### ISSUE TITLE
Sammlung von Auffälligkeiten (Review und Polishing)

### ISSUE THREAD

**Issue by gorkemg** [Schulconnex/Schulconnex#235]
Auffälligkeiten sammeln und zur Diskussion aufbereiten.

Dieses Issue ist Teil von #227 Review und Polishing der Spezifikation.

**Comment by gorkemg** [comment]
Die Kategorie "Schnittstellendefinition" klingt unpassend und könnte verwirrend sein, da der Inhalt hauptsächlich HTTP-Status-Codes beschreibt.
Eine Umbenennung und Umstrukturierung wäre empfehlenswert.

Zum Beispiel:
"Schnittstellendefinitionen" umbenennen in "Status-Codes". Die Unterseiten "Fehlerbehandlungen" und "Validierung" könnten in "Status-Codes" mit aufgenommen werden, so dass sie als Unterkategorien in "Status-Codes" zu finden sind.

Aufbau wäre dann:
Status-Codes
- Allgemeine Festlegungen
- Erfolgreiche Ausführung
- Fehlerbehandlungen
- Validierung

**Comment by gorkemg** [comment]
Auch "Schnittstellen für Quellsysteme und Dienste" könnte vereinfacht werden.

Statt "Schnittstellen für Quellsysteme und Dienste" könnte man die Unterseiten aufteilen in „Autorisierung und Authentifizierung“ und "Erweitert".

Der Aufbau würde wie folgt aussehen:
- Autorisierung und Authentifizierung
   - Autorisierung Dienstanbieter
   - Autorisierung Quellsysteme
- Erweitert
  - OIDC-Claims
  - Herstellereigene Attribute

**Comment by bwhdien** [comment]
> Die Kategorie "Schnittstellendefinition" klingt unpassend und könnte verwirrend sein, da der Inhalt hauptsächlich HTTP-Status-Codes beschreibt. Eine Umbenennung und Umstrukturierung wäre empfehlenswert.
> 
> Zum Beispiel: "Schnittstellendefinitionen" umbenennen in "Status-Codes". Die Unterseiten "Fehlerbehandlungen" und "Validierung" könnten in "Status-Codes" mit aufgenommen werden, so dass sie als Unterkategorien in "Status-Codes" zu finden sind.
> 
> Aufbau wäre dann: Status-Codes
> 
> * Allgemeine Festlegungen
> * Erfolgreiche Ausführung
> * Fehlerbehandlungen
> * Validierung

Vorschlag für den Titel "Allgemeine Festlegungen für die REST-Schnittstelle"

**Comment by bwhdien** [comment]
> Auch "Schnittstellen für Quellsysteme und Dienste" könnte vereinfacht werden.
> 
> Statt "Schnittstellen für Quellsysteme und Dienste" könnte man die Unterseiten aufteilen in „Autorisierung und Authentifizierung“ und "Erweitert".
> 
> Der Aufbau würde wie folgt aussehen:
> 
> * Autorisierung und Authentifizierung
>   
>   * Autorisierung Dienstanbieter
>   * Autorisierung Quellsysteme
> * Erweitert
>   
>   * OIDC-Claims
>   * Herstellereigene Attribute

Jede API (Dienste, QS) sollte einen Abschnitt "Authentisierung und Autorisierung" haben, die Dienste-API den Abschnitt "OIDC". "Anbietersp. Attr." geht wohl in den gemeinsamen Teil.

**Comment by aldafu** [comment]
PR zum neu diskutierten Menüaufbau bzgl Schnittstelel/REST-API und Auth und "Erweitert": #261 

![grafik](https://github.com/user-attachments/assets/1ef3928d-314c-41ab-862d-cccc157fc6a3)

**Comment by gorkemg** [comment]
Dieses Issue wurde durch die Umstrukturierung #259 und der Menüanpassung #261 und auch #256 erledigt und kann geschlossen werden.
