### ISSUE TITLE
Mögliche Umstrukturierung (Review und Polishing)

### ISSUE THREAD

**Issue by gorkemg** [Schulconnex/Schulconnex#236]
Umstrukturierungen vorschlagen, insb. da die Spezifikationen aus einem großen fortlaufenden Dokument stammt, nun aber einzelne Teile als Webseite separat aufgerufen werden können.

Dieses Issue ist Teil von #227 Review und Polishing der Spezifikation.

**Comment by bwhdien** [comment]
Bitte auch https://github.com/Schulconnex/Schulconnex/issues/131 beachten

**Comment by christopherkrauss** [comment]
In diesem Kontext möchte ich noch ein sichtbares Tag (Markierung, Label o.ä.) vorschlagen, das auf jeder Seite zeigt, ob der Spezifikationsteil sich nur auf Dienste, nur auf Quellsysteme oder auf beide bezieht.

**Comment by O-Fischer** [comment]
+ Mögliche Anwendung dieser Tagging-Methode auch auf die einzelnen Fehlercodes, wenn man sie alle unter "Dienste" und "Quellsysteme" in einem zusätzlichen Feld "Allgemein" abbildet

**Comment by bwhdien** [comment]
Die Umstrukturierung sollte im Zusammenhang mit #131 angegangen werden, wodurch normative (Datenmodell, JSON-Schema, REST-Endpunkte) und nichtnormative Teile (Best-practice, Authentisierungsmethoden?) getrennt werden. GGf. die normativen Teile durch sichtbare Tags (Markierung, Label, Hinweis auf der Seite) kennzeichnen.

**Comment by bwhdien** [comment]
Option 3 scheint sinnvoll, aber es wäre zu überlegen, ob nicht zusätzlich ein weiterer Bereich (Allgemeines?, Motivation?, Projekt?) angelegt wird, in dem die Gemeinsamkeiten der beiden APIs dargestellt werden (auch gem. Datenmodell, gem. Wertelisten, Kapitel zu anbieterspezifischen Attributen, Glossar, Löschkonzept).
