### ISSUE TITLE
Quick-Start / Schnelleinstieg für Entwickler

### ISSUE THREAD

**Issue by gorkemg** [Schulconnex/Schulconnex#243]
Für Entwickler ist ein "Quick-Start" bzw. ein "Schnelleinstieg" sehr praktisch, um einen groben Überblick zu bekommen.
Diese neue Seite kann ins Hauptmenü zwischen Einleitung und Allgemeines aufgenommen werden.

Da wir zeitgleich auch über eine Umstrukturierung sprechen wäre es denkbar "Schnelleinstieg" später zu verschieben.

**Comment by aldafu** [comment]
Dieses Issue ist Teil von https://github.com/Schulconnex/Schulconnex/issues/227 Review und Polishing der Spezifikation.
