### ISSUE TITLE
Trenne Unterdatenmodelle

### ISSUE THREAD

**Issue by gorkemg** [Schulconnex/Schulconnex#244]
Es gibt Objekte in der API, die keine eigene Definition als Datenmodell besitzen, wie beispielsweise _Faecher,_ _Referenzgruppe_ und _Erreichbarkeit_.
Für diese Datenmodelle sollen ebenfalls Markdown Dateien erstellt werden und an passenden Stellen in der Spezifikation verlinkt werden.

**Comment by aldafu** [comment]
Dieses Issue ist Teil von https://github.com/Schulconnex/Schulconnex/issues/227 Review und Polishing der Spezifikation.
