### ISSUE TITLE
String-Standards im Glossar

### ISSUE THREAD

**Issue by gorkemg** [Schulconnex/Schulconnex#245]
In der Spezifikation werden mehrere unterschiedliche Standards für Strings vorausgesetzt.
- UTF-8
- DIN 91379.A
- DIN 91379.B
- DIN 91379.C

Diese Standards werden im Glossar aufgenommen und an passenden Stellen verlinkt.
Folgende Webseite kann als Referenz benutzt werden: https://www.xoev.de/string-latin-4813

**Comment by aldafu** [comment]
Dieses Issue ist Teil von https://github.com/Schulconnex/Schulconnex/issues/227 Review und Polishing der Spezifikation.
