### ISSUE TITLE
Links in herunterlandbaren YAML Dateien entfernen

### ISSUE THREAD

**Issue by ChristianFuhrhop** [Schulconnex/Schulconnex#257]
In den herunterladbaren YAML Dateien (api-qs.yaml und api-dienste.yaml) sind nocht diverse Links, welche auf der Webseite Sinn machen (wie Siehe [Fehlerbehandlung](../../../schnittstellendefinition/fehlerbehandlung) oder  [Person](../../../datenmodell/person) ), aber bei den zusammengesetzten, herunterladbaren YAML Dateien nicht mehr funktionieren.

Da Entwickler YAML Dateien nur aus technischen Gründen (zum automatischen Erzeugen von Stubs) herunterladen werden, werden dort die Links nicht gebraucht, aber sollte jemand die YAML Dateien mal mit OpenAPI anschauen, sehen 'tote' Links immer schlecht aus.

Hier sollte nach dem Erstellen der beiden YAML-Dateien noch ein Skript drüber laufen, welches die Links einfach entfernt.

**Comment by bwhdien** [comment]
Wie heute besprochen, sollte das Skript die relativen Links gegen absolute austauschen. 
Die absoluten beginnen mit httsp://schulconnex.de
